basePath: /
definitions:
  schemas.StudentResponse:
    properties:
      active:
        type: boolean
      age:
        type: integer
      cpf:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Esta é uma API de Students com Gin + Swagger
  title: Students API
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: Faz uma requisição para health check da API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Ping example
      tags:
      - Ping
  /students:
    get:
      consumes:
      - application/json
      description: Busca os dados de todos os estudantes na API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              items:
                $ref: '#/definitions/schemas.StudentResponse'
              type: array
            type: object
      summary: get all students
      tags:
      - Students
swagger: "2.0"
