basePath: /
host: localhost:8080
info:
  contact: {}
  description: Esta é uma API de Students com Gin + Swagger
  title: Students API
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: Faz uma requisição para health check da API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Ping example
      tags:
      - Ping
swagger: "2.0"
